//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp2007_Assignment2_GameTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekDetail
    {
        public int Id { get; set; }
        public System.DateTime GameDate { get; set; }
        public string GameName { get; set; }
        public string GameDescription { get; set; }
        public int TotalPoints { get; set; }
        public decimal TotalSpectators { get; set; }
        public string Team1Name { get; set; }
        public string Team1Description { get; set; }
        public int Team1PointScored { get; set; }
        public int Team1PointLoss { get; set; }
        public string Team2Name { get; set; }
        public string Team2Description { get; set; }
        public int Team2PointScored { get; set; }
        public int Team2PointLoss { get; set; }
        public string WiningTeam { get; set; }
        public int UserID { get; set; }
    }
}
